---
- name: create user
  user: name={{ username }} shell=/bin/bash createhome=yes

- name: 分发公钥至各节点
  authorized_key: user={{ username }} key="{{ lookup('file', 'id_rsa.pub') }}"

- name: update sudoers file
  lineinfile:
    dest: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    insertafter: EOF
    regexp: '^{{ username }} .*'
    state: present    
    
- file:
    path: "{{ item.value }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755
  with_dict: "{{ disks }}"

- name: format datanode disks
  filesystem: fstype=ext4 dev="{{ item.key }}" force=true
  with_dict: "{{ disks }}"

- name: mount datanode disks
  mount:
    path: "{{ item.value }}"
    src: "{{ item.key }}"
    fstype: ext4
    opts: "defaults,noatime,nobarrier"
    state: mounted
  with_dict: "{{ disks }}"

- name: mkdir directory for es data
  file: dest=/{{ item.value }}/es mode=0755 state=directory owner=elasticsearch group=elasticsearch
  with_dict: "{{ disks }}"